### ISSUE TITLE
Bury Corpses not working

### ISSUE THREAD

**Issue by SlyKyti** [HAHAYOUDEAD/TinyTweaks#1]
Right click on Windows Mouse does nothing. Left opens the corpse.
Checked keybindings. Control settings. Made sure I have last version including Required Dependencies (ModData).
I am using Melon Loader 0.6.0  "Show Alpha Pre-Releases".
Steam Version v2.08 Survival.
Thanks for your mod.

**Comment by HAHAYOUDEAD** [comment]
what other mods do you have installed? show your latest.log from TheLongDark/MelonLoader/

**Comment by HAHAYOUDEAD** [comment]
actually nevermind, I think 2.07 update broke it. Too bad you are the only one that actually said you have ModData installed and still having this issue. Gonna investigate, thanks

**Comment by HAHAYOUDEAD** [comment]
fixed in 1.0.2
