### ISSUE TITLE
Items reset inside buildings/when sleeping/loading game

### ISSUE THREAD

**Issue by MariaWB** [HAHAYOUDEAD/TinyTweaks#2]
After I started using this mod, if I moved or placed something inside a building, left it and then reentered, what I placed would be gone and what I moved would be back in its original location.

Same thing after each time I slept, and every time I loaded the game.

**Comment by HAHAYOUDEAD** [comment]
did you install ModData?

**Comment by MariaWB** [comment]
Dependencies listed is ModSettings, and I have that one

![image](https://user-images.githubusercontent.com/130254657/230796378-331fb83a-e43e-4639-a2fd-d22c016f8b96.png)

**Comment by HAHAYOUDEAD** [comment]
Dependencies vary for each TinyTweak, it's mentioned both on main page here and on Xpazeman's mod list. Your problem means you're using the one that requires ModData, and you don't have it

**Comment by MariaWB** [comment]
When I downloaded it, it only said it needed mod setting - this is a screenshot I took a few days ago.
![image](https://user-images.githubusercontent.com/130254657/231877995-d930de4e-0c13-48e1-a0e6-c5a878323636.png)

**Comment by HAHAYOUDEAD** [comment]
Might be a bug with the site, I have no idea. It needed that dependency from the get go, and I see it on my side

**Comment by MariaWB** [comment]
I see it now, too. It's weird

**Comment by HAHAYOUDEAD** [comment]
so is all good now?

**Comment by MariaWB** [comment]
Yes!
