### ISSUE TITLE
Acorns included?

### ISSUE THREAD

**Issue by H34VY-R41N** [HAHAYOUDEAD/TinyTweaks#3]
First of all I wanted to thank you for all of your mods, I think I use all of them but the Regrow. 
The question is - do acorns respawn with that mod too? I couldn't find the detailed description, I'm sorry, if it's listed somewhere.

**Comment by HAHAYOUDEAD** [comment]
it's not listed, but people confirmed it's working with acorns. I believe it had some visual issues with it though, like not always showing acorns even when respawned or something like that

**Comment by H34VY-R41N** [comment]
Thanks
